name: Deploy DSATracker App

on:
  # This section enables manual execution of the workflow
  workflow_dispatch:
    inputs:
      branch:
        description: 'Branch to deploy from (e.g., master)'
        required: true
        default: 'master'

permissions:
  id-token: write
  contents: write
  pages: write

jobs:
  build-and-deploy:
    environment:
      name: github-pages

    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        # Use the branch input from the manual trigger
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.inputs.branch }}

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Deploy to GitHub Pages
        uses: skywarth/vite-github-pages-deployer@v1.5.0
        with:
          public_base_path: /DSA-Problems-Tracker/  # This is the base
          build_path: ./dist
          install_phase_node_env: dev
          build_phase_node_env: production
          package_manager: npm
          artifact_name: github-pages
          debug_mode: false
          working_path: ./