name: Deploy DSATracker App

on:
  # This section enables manual execution of the workflow
  workflow_dispatch:
    inputs:
      branch:
        description: 'Branch to deploy from (e.g., master)'
        required: true
        default: 'master'

permissions:
  id-token: write
  contents: write
  pages: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        # Use the branch input from the manual trigger
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.inputs.branch }}

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Build project
        run: npm run build

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
          # Use the branch input for clarity in the deployment logs
          commit_message: Deploying from ${{ github.event.inputs.branch }} by @${{ github.actor }}